name: Weekly Map Update

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run the update script
        env:
          DW_API_KEY: ${{ secrets.DW_API_KEY }}
        run: python overdose_update.py
